#!/usr/bin/env python3
"""Record primary-source reclassification pressure for P0 body failures."""
from __future__ import annotations
import json
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data/derived';REPORT=ROOT/'reports/p0_body_failure_source_reclassification_review_v01.md'
def main():
 rows=[
 {'galaxy':'UGC04305','aliases':'Holmberg II;DDO 50','current_family':'K_scale_tail_spiral','source_evidence':'HI body contains large holes and turbulence with an inferred large driving scale; simple smooth tail is incomplete','source':'Dib & Burkert (2005), arXiv:astro-ph/0402593; Hunter et al. (2023), arXiv:2309.01268','proposed_body_subfamily':'K_scale_tail_turbulent_holey','reclassification_pressure':'HIGH','channel_relevance':'internal body turbulence/feedback must be separated before any coherence or channel-capacity attribution'},
 {'galaxy':'UGC07577','aliases':'DDO 125','current_family':'K_scale_tail_spiral','source_evidence':'possible tidal dwarf associated with NGC 4449 HI streamers; published mass-model fit did not converge','source':'van den Bosch & Swaters (2001), MNRAS 325, 1017; WHISP overview','proposed_body_subfamily':'K_disturbed_tidal_history','reclassification_pressure':'HIGH','channel_relevance':'environment/history belongs to body state first; not a clean sightline-channel residual'},
 {'galaxy':'NGC4088','aliases':'UGC 7081','current_family':'K_thick_flared','source_evidence':'strongly distorted disk with asymmetric warp and vigorous star formation','source':'Verheijen & Sancisi (2001), A&A 370, 765','proposed_body_subfamily':'K_warped_asymmetric_disturbed_disk','reclassification_pressure':'HIGH','channel_relevance':'warp/asymmetry is intrinsic source structure unless a separate transfer measurement survives'},
 {'galaxy':'NGC4389','aliases':'UGC 7514','current_family':'K_thick_flared','source_evidence':'bar dominates stellar, HI, Halpha morphology and kinematics','source':'Korsaga et al. (2016), MNRAS 460, 689','proposed_body_subfamily':'K_bar_dominated_non_circular','reclassification_pressure':'HIGH','channel_relevance':'bar streaming/non-circular motion is a conventional body/dynamics explanation before channel attribution'},
 ]
 out=pd.DataFrame(rows);out['source_native_family_promoted']=False;out['inspected_holdout_rescoring_allowed']=False;out.to_csv(DATA/'p0_body_failure_source_reclassification_review_v01.csv',index=False);result={'schema':'tau-core.paper8.p0-body-failure-source-reclassification-review.v01','status':'P0_FAILURES_SHOW_SOURCE_BACKED_RECLASSIFICATION_PRESSURE','n_p0':len(out),'n_high_pressure':int((out.reclassification_pressure=='HIGH').sum()),'proposed_subfamilies':dict(zip(out.galaxy,out.proposed_body_subfamily)),'inspected_holdout_rescoring_allowed':False,'next_use':'freeze these subfamily definitions and observables on a new or untouched source packet before scoring','claim_boundary':'post-score primary-source review; reclassification pressure only, not retrospective endpoint repair or channel detection'};(DATA/'p0_body_failure_source_reclassification_review_v01.json').write_text(json.dumps(result,indent=2)+'\n');lines=['# P0 body-failure source reclassification review v01','',f"Status: `{result['status']}`",'']+[f"- `{r.galaxy}` -> `{r.proposed_body_subfamily}`: {r.source_evidence} Source: {r.source}." for r in out.itertuples()]+['','All four cases exert high source-backed pressure against the coarse current family. No inspected holdout rescoring is allowed.'];REPORT.write_text('\n'.join(lines)+'\n');print(result['status'])
if __name__=='__main__':main()
