#!/usr/bin/env python3
"""Recompute LITTLE THINGS score summaries after physical-alias exclusion."""
from __future__ import annotations
import json
from pathlib import Path
import pandas as pd
ROOT=Path(__file__).resolve().parents[1];DATA=ROOT/'data/derived';REPORT=ROOT/'reports/little_things_alias_corrected_kernel_score_v01.md'
def summary(x):
 return {'n_galaxies':len(x),'n_points':int(x.n_points.sum()),'mean_rmse_km_s':{'tau_matched':float(x.rmse_tau_matched.mean()),'wrong_family_mean':float(x.rmse_wrong_family_mean.mean()),'tpg_v6':float(x.rmse_tpg_v6.mean()),'mond':float(x.rmse_mond.mean()),'newton':float(x.rmse_newton.mean())},'win_fraction':{'wrong_family_mean':float(x.matched_beats_wrong.mean()),'best_wrong_family':float(x.matched_beats_best_wrong.mean()),'tpg_v6':float(x.matched_beats_tpg.mean()),'mond':float(x.matched_beats_mond.mean()),'newton':float(x.matched_beats_newton.mean())}}
def main():
 scores=pd.read_csv(DATA/'little_things_prospective_kernel_scores_by_galaxy_v01.csv');audit=pd.read_csv(DATA/'little_things_alias_independence_audit_v01.csv');bad=set(audit.loc[audit.alias_physical_overlap,'galaxy']);corrected=scores[~scores.galaxy.isin(bad)].copy();primary=corrected[corrected.inclination_deg>=40];result={'schema':'tau-core.paper8.little-things-alias-corrected-kernel-score.v01','status':'EXTERNAL_SCORE_RECOMPUTED_AFTER_ALIAS_EXCLUSION','excluded_alias_overlaps':sorted(set(scores.galaxy)&bad),'all_corrected':summary(corrected),'primary_inclination_ge_40':summary(primary),'prospective_claim_allowed':False,'reason':'the original exact-name gate missed physical aliases; corrected set is independent by SIMBAD identity but was selected after original score inspection','claim_boundary':'alias-corrected retrospective external score; not prospective validation and not a test of new post-score subfamily labels'};(DATA/'little_things_alias_corrected_kernel_score_v01.json').write_text(json.dumps(result,indent=2)+'\n');corrected.to_csv(DATA/'little_things_alias_corrected_kernel_scores_by_galaxy_v01.csv',index=False);p=result['primary_inclination_ge_40'];REPORT.write_text(f"# LITTLE THINGS alias-corrected kernel score v01\n\nStatus: `{result['status']}`\n\nExcluded hidden physical overlaps: `{result['excluded_alias_overlaps']}`. The corrected primary lane has `{p['n_galaxies']}` galaxies and `{p['n_points']}` points. Matched wins versus wrong mean, best wrong, TPG, MOND, and Newton are `{p['win_fraction']['wrong_family_mean']:.3f}`, `{p['win_fraction']['best_wrong_family']:.3f}`, `{p['win_fraction']['tpg_v6']:.3f}`, `{p['win_fraction']['mond']:.3f}`, `{p['win_fraction']['newton']:.3f}`. The correction is retrospective; prospective validation is not claimed.\n");print(result['status'])
if __name__=='__main__':main()
